### ISSUE TITLE
Clarification when using prive keys during the installation

### ISSUE THREAD

**Issue by jaimedantas** [pacslab/EECS6446_Project#5]
When installing **k3sup** using the private keys provided, we need to specify them when running the command.

**Step 2: Installing Kubernetes**

Command:
```
k3sup join --ip $WORKER_IP --user $WORKER_USER --server-ip $MASTER_IP --server-user $MASTER_USER --k3s-extra-args "--node-external-ip $WORKER_IP --node-ip $WORKER_IP" --k3s-channel stable --print-command
```

**Comment by nimamahmoudi** [comment]
Thanks Jaime, we actually mentioned that we assume that the key is located at `.ssh/id_rsa` and `.ssh/id_rsa.pub`, but setting them explicitly makes it easier to follow for the students. Please go ahead and make a pull request so that we can import your changes into the tutorial.

**Comment by nimamahmoudi** [comment]
The issue seems to be resolved, so I will close this issue.
